
services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - SECRET_KEY=django-insecure-i&=c&7lc81pl@o-oi$=#@isu%_x@a)@ogc#3c&zj@5&c0m$_0l
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --port 6380

  worker:
    build: .
    container_name: celery_worker
    command: celery -A django_app worker --loglevel=info -P eventlet
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0
    restart: unless-stopped

