version: '3'
services:
  web:
    build: .
    container_name: codelintpr_app
    image: sathwikshetty50/codelintpr
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0
      - ALLOWED_HOSTS=*
      - DEBUG=True
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 & 
             celery -A django_app worker --loglevel=info -P eventlet"
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: codelintpr_redis
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --port 6380
    networks:
      - app-network

networks:
  app-network:
    driver: bridge